spring:
  profiles: prod
  r2dbc:
    url: jdbc:mysql://127.0.0.1:3306/dokotlin?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password:
    pool:
      max-size: 100
      validation-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    #org.springframework.r2dbc: DEBUG
    org.hibernate.SQL: debug
    #com.yolo.dokotlin: debug
    org.hibernate.type: trace

yolo:
  service:
    host: 192.168.0.13
    port: 1341
